### ISSUE TITLE
Add autocomplete to the districts

### ISSUE THREAD

**Issue by dchaplinsky** [dimanech/form#4]
Here goes the data:

Бахчисарайський
Білогірський
Джанкойський
Кіровський
Красногвардійський
Красноперекопський
Ленінський
Нижньогірський
Первомайський
Роздольненський
Сакський
Сімферопольський
Совєтський
Чорноморський
Алушта
Армянськ
Красноперекопськ
Джанкой
Євпаторія
Керч
Саки
Сімферополь
Судак
Феодосія
Ялта
Барський
Бершадський
Вінницький
Гайсинський
Жмеринський
Іллінецький
Калинівський
Козятинський
Крижопільський
Липовецький
Літинський
Могилів-Подільський
Мурованокуриловецький
Немирівський
Оратівський
Піщанський
Погребищенський
Теплицький
Тиврівський
Томашпільський
Тростянецький
Тульчинський
Хмільницький
Чернівецький
Чечельницький
Шаргородський
Ямпільський
Вінниця
Жмеринка
Козятин
Ладижин
Хмільник
Володимир-Волинський
Горохівський
Іваничівський
Камінь-Каширський
Ківерцівський
Ковельський
Локачинський
Луцький
Любешівський
Любомльський
Маневицький
Ратнівський
Рожищенський
Старовижівський
Турійський
Шацький
Ковель
Луцьк
Нововолинськ
Апостолівський
Васильківський
Верхньодніпровський
Дніпропетровський
Криворізький
Криничанський
Магдалинівський
Межівський
Нікопольський
Новомосковський
Павлоградський
Петриківський
Петропавлівський
Покровський
П'ятихатський
Синельниківський
Солонянський
Софіївський
Томаківський
Царичанський
Широківський
Юр'ївський
Вільногірськ
Дніпродзержинськ
Дніпропетровськ
Жовті Води
Кривий Ріг
Марганець
Нікополь
Новомосковськ
Орджонікідзе
Павлоград
Першотравенськ
Синельникове
Тернівка
Амвросіївський
Артемівський
Великоновосілківський
Волноваський
Володарський
Добропільський
Костянтинівський
Красноармійський
Краснолиманський
Мар'їнський
Новоазовський
Олександрівський
Першотравневий
Слов'янський
Старобешівський
Тельманівський
Шахтарський
Ясинуватський
Авдіївка
Артемівськ
Вугледар
Горлівка
Дебальцеве
Дзержинськ
Димитров
Добропілля
Докучаєвськ
Донецьк
Дружківка
Єнакієве
Жданівка
Кіровське
Костянтинівка
Краматорськ
Красний Лиман
Красноармійськ
Макіївка
Маріуполь
Новогродівка
Селидове
Слов'янськ
Сніжне
Торез
Харцизьк
Шахтарськ
Ясинувата
Андрушівський
Баранівський
Бердичівський
Брусилівський
Володарсько-Волинський
Романівський
Ємільчинський
Житомирський
Коростенський
Коростишівський
Лугинський
Любарський
Малинський
Народицький
Новоград-Волинський
Овруцький
Олевський
Попільнянський
Радомишльський
Ружинський
Червоноармійський
Черняхівський
Чуднівський
Бердичів
Житомир
Коростень
Малин
Берегівський
Великоберезнянський
Виноградівський
Воловецький
Іршавський
Міжгірський
Мукачівський
Перечинський
Рахівський
Свалявський
Тячівський
Ужгородський
Хустський
Берегове
Мукачеве
Ужгород
Хуст
Чоп
Бердянський
Василівський
Великобілозерський
Веселівський
Вільнянський
Гуляйпільський
Запорізький
Кам'янсько-Дніпровський
Куйбишевський
Мелітопольський
Михайлівський
Новомиколаївський
Оріхівський
Пологівський
Приазовський
Приморський
Розівський
Токмацький
Чернігівський
Якимівський
Бердянськ
Енергодар
Запоріжжя
Мелітополь
Токмак
Богородчанський
Верховинський
Галицький
Городенківський
Долинський
Калуський
Коломийський
Косівський
Надвірнянський
Рогатинський
Рожнятівський
Снятинський
Тисменицький
Тлумацький
Болехів
Івано-Франківськ
Калуш
Коломия
Яремче
Баришівський
Білоцерківський
Богуславський
Бориспільський
Бородянський
Броварський
Вишгородський
Згурівський
Іванківський
Кагарлицький
Києво-Святошинський
Макарівський
Миронівський
Обухівський
Переяслав-Хмельницький
Поліський
Рокитнянський
Сквирський
Ставищенський
Таращанський
Тетіївський
Фастівський
Яготинський
Бориспіль
Березань
Біла Церква
Бровари
Буча
Васильків
Ірпінь
Обухів
Прип'ять
Ржищів
Славутич
Фастів
Бобринецький
Вільшанський
Гайворонський
Голованівський
Добровеличківський
Знам'янський
Кіровоградський
Компаніївський
Маловисківський
Новгородківський
Новоархангельський
Новомиргородський
Новоукраїнський
Олександрійський
Онуфріївський
Петрівський
Світловодський
Ульяновський
Устинівський
Знам'янка
Кіровоград
Олександрія
Світловодськ
Антрацитівський
Біловодський
Білокуракинський
Краснодонський
Кремінський
Лутугинський
Марківський
Міловський
Новоайдарський
Новопсковський
Перевальський
Попаснянський
Сватівський
Свердловський
Слов'яносербський
Станично-Луганський
Старобільський
Троїцький
Алчевськ
Антрацит
Брянка
Кіровськ
Красний Луч
Краснодон
Лисичанськ
Луганськ
Первомайськ
Ровеньки
Рубіжне
Свердловськ
Сєверодонецьк
Стаханов
Бродівський
Буський
Городоцький
Дрогобицький
Жидачівський
Жовківський
Золочівський
Кам'янка-Бузький
Миколаївський
Мостиський
Перемишлянський
Пустомитівський
Радехівський
Самбірський
Сколівський
Сокальський
Старосамбірський
Стрийський
Турківський
Яворівський
Борислав
Дрогобич
Львів
Моршин
Новий Розділ
Самбір
Стрий
Трускавець
Червоноград
Арбузинський
Баштанський
Березанський
Березнегуватський
Братський
Веселинівський
Вознесенський
Врадіївський
Доманівський
Єланецький
Жовтневий
Казанківський
Кривоозерський
Новобузький
Новоодеський
Очаківський
Снігурівський
Вознесенськ
Миколаїв
Очаків
Южноукраїнськ
Ананьївський
Арцизький
Балтський
Березівський
Білгород-Дністровський
Біляївський
Болградський
Великомихайлівський
Іванівський
Ізмаїльський
Кілійський
Кодимський
Комінтернівський
Котовський
Красноокнянський
Любашівський
Овідіопольський
Ренійський
Роздільнянський
Савранський
Саратський
Тарутинський
Татарбунарський
Фрунзівський
Ширяївський
Ізмаїл
Іллічівськ
Котовськ
Одеса
Теплодар
Южне
Великобагачанський
Гадяцький
Глобинський
Гребінківський
Диканський
Зіньківський
Карлівський
Кобеляцький
Козельщинський
Котелевський
Кременчуцький
Лохвицький
Лубенський
Машівський
Миргородський
Новосанжарський
Оржицький
Пирятинський
Полтавський
Решетилівський
Семенівський
Хорольський
Чорнухинський
Чутівський
Шишацький
Комсомольськ
Кременчук
Лубни
Миргород
Полтава
Березнівський
Володимирецький
Гощанський
Демидівський
Дубенський
Дубровицький
Зарічненський
Здолбунівський
Корецький
Костопільський
Млинівський
Острозький
Радивилівський
Рівненський
Рокитнівський
Сарненський
Дубно
Кузнецовськ
Острог
Рівне
Білопільський
Буринський
Великописарівський
Глухівський
Конотопський
Краснопільський
Кролевецький
Лебединський
Липоводолинський
Недригайлівський
Охтирський
Путивльський
Роменський
Середино-Будський
Сумський
Шосткинський
Охтирка
Глухів
Конотоп
Лебедин
Ромни
Суми
Шостка
Бережанський
Борщівський
Бучацький
Гусятинський
Заліщицький
Збаразький
Зборівський
Козівський
Кременецький
Лановецький
Монастириський
Підволочиський
Підгаєцький
Теребовлянський
Тернопільський
Чортківський
Шумський
Тернопіль
Балаклійський
Барвінківський
Близнюківський
Богодухівський
Борівський
Валківський
Великобурлуцький
Вовчанський
Дворічанський
Дергачівський
Зачепилівський
Зміївський
Ізюмський
Кегичівський
Коломацький
Красноградський
Краснокутський
Куп'янський
Лозівський
Нововодолазький
Печенізький
Сахновщинський
Харківський
Чугуївський
Шевченківський
Ізюм
Куп'янськ
Лозова
Люботин
Харків
Чугуїв
Бериславський
Білозерський
Великолепетиський
Великоолександрівський
Верхньорогачицький
Високопільський
Генічеський
Голопристанський
Горностаївський
Каланчацький
Каховський
Нижньосірогозький
Нововоронцовський
Новотроїцький
Скадовський
Цюрупинський
Чаплинський
Каховка
Нова Каховка
Херсон
Віньковецький
Волочиський
Деражнянський
Дунаєвецький
Ізяславський
Кам'янець-Подільський
Красилівський
Летичівський
Новоушицький
Полонський
Славутський
Старокостянтинівський
Старосинявський
Теофіпольський
Хмельницький
Чемеровецький
Шепетівський
Ярмолинецький
Нетішин
Славута
Старокостянтинів
Шепетівка
Городищенський
Драбівський
Жашківський
Звенигородський
Золотоніський
Кам'янський
Канівський
Катеринопільський
Корсунь-Шевченківський
Лисянський
Маньківський
Монастирищенський
Смілянський
Тальнівський
Уманський
Христинівський
Черкаський
Чигиринський
Чорнобаївський
Шполянський
Ватутіне
Золотоноша
Канів
Сміла
Умань
Черкаси
Вижницький
Герцаївський
Глибоцький
Заставнівський
Кельменецький
Кіцманський
Новоселицький
Путильський
Сокирянський
Сторожинецький
Хотинський
Новодністровськ
Чернівці
Бахмацький
Бобровицький
Борзнянський
Варвинський
Городнянський
Ічнянський
Козелецький
Коропський
Корюківський
Куликівський
Менський
Ніжинський
Новгород-Сіверський
Носівський
Прилуцький
Ріпкинський
Сосницький
Срібнянський
Талалаївський
Щорський
Ніжин
Прилуки
Чернігів
Голосіївський
Дарницький
Деснянський
Дніпровський
Оболонський
Печерський
Подільський
Святошинський
Солом'янський
Балаклавський
Гагарінський
Нахімовський
Калінінський
Микитівський
Центральноміський
Баглійський
Заводський
Амур-Нижньодніпровський
Бабушкінський
Індустріальний
Самарський
Будьонівський
Ворошиловський
Київський
Петровський
Пролетарський
Богунський
Корольовський
Комунарський
Орджонікідзевський
Хортицький
Автозаводський
Крюківський
Дзержинський
Довгинцівський
Інгулецький
Саксаганський
Тернівський
Кам'янобрідський
Залізничний
Личаківський
Сихівський
Франківський
Гірницький
Червоногвардійський
Іллічівський
Корабельний
Центральний
Малиновський
Суворовський
Октябрський район
Зарічний
Ковпаківський
Московський
Фрунзенський
Червонозаводський
Комсомольський
Придніпровський
Соснівський
Садгірський
Новозаводський

**Comment by dimanech** [comment]
Added
